stages:
  - prepare
  - tests
  - deploy

composer:
  stage: prepare
  image: thecodingmachine/php:8.1-v4-cli-node16
  script:
    - php -v
    - composer config -g cache-dir "$CI_PROJECT_DIR/.composer-cache"
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
    expire_in: 30 days
    when: on_success
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .composer-cache

phpunit:
  stage: tests
  image: thecodingmachine/php:8.1-v4-cli-node16
  script:
    - XDEBUG_MODE=coverage vendor/bin/phpunit
  dependencies:
    - composer
  coverage: '/^\s*Lines:\s*\d+.\d+\%./'
  variables:
    PHP_EXTENSIONS: xdebug
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

php-cs-fixer:
  stage: tests
  image: thecodingmachine/php:8.1-v4-cli-node16
  script:
    - ./vendor/bin/php-cs-fixer fix -v --dry-run --format=gitlab --using-cache=no | tee gl-cs-fixer.json
  dependencies:
    - composer
  allow_failure: true
  artifacts:
    reports:
      codequality: gl-cs-fixer.json

publish:
  image: curlimages/curl:latest
  stage: deploy
  only:
    - tags
  script:
    - 'curl -sS --show-error --header "Job-Token: $CI_JOB_TOKEN" --data tag=${CI_COMMIT_TAG} "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
