stages:
  - prepare
  - tests

composer:
  stage: prepare
  image: thecodingmachine/php:8.1-v4-cli-node16
  script:
    - php -v
    - composer config -g cache-dir "$CI_PROJECT_DIR/.composer-cache"
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
    expire_in: 30 days
    when: on_success
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .composer-cache

phpunit:
  stage: tests
  image: thecodingmachine/php:8.1-v4-cli-node16
  script:
    - vendor/bin/phpunit
  dependencies:
    - composer
  artifacts:
    reports:
      junit: junit.xml
